// Package iaas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/do87/stackit-client-generator version v0.0.2 DO NOT EDIT.
package iaas

import (
	"net/url"
	"strings"

	contracts "github.com/SchwarzIT/community-stackit-go-client/pkg/contracts"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/area"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/backups"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/flavors"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/images"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/keypairs"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/network"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/probes"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/project"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/request"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/services/iaas-api/v1/servers"
)

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// list of connected client services
	Area     *area.Client
	Backups  *backups.Client
	Flavors  *flavors.Client
	Images   *images.Client
	Keypairs *keypairs.Client
	Network  *network.Client
	Probes   *probes.Client
	Project  *project.Client
	Request  *request.Client
	Servers  *servers.Client

	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client contracts.BaseClientInterface
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

func NewRawClient(server string, opts ...ClientOption) (*Client, error) {
	// create a factory client
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}

	client.Area = area.NewRawClient(server, client.Client)
	client.Backups = backups.NewRawClient(server, client.Client)
	client.Flavors = flavors.NewRawClient(server, client.Client)
	client.Images = images.NewRawClient(server, client.Client)
	client.Keypairs = keypairs.NewRawClient(server, client.Client)
	client.Network = network.NewRawClient(server, client.Client)
	client.Probes = probes.NewRawClient(server, client.Client)
	client.Project = project.NewRawClient(server, client.Client)
	client.Request = request.NewRawClient(server, client.Client)
	client.Servers = servers.NewRawClient(server, client.Client)

	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer contracts.BaseClientInterface) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponses builds on rawClientInterface to offer response payloads
type ClientWithResponses struct {
	Client *Client

	// list of connected client services
	Area     *area.ClientWithResponses
	Backups  *backups.ClientWithResponses
	Flavors  *flavors.ClientWithResponses
	Images   *images.ClientWithResponses
	Keypairs *keypairs.ClientWithResponses
	Network  *network.ClientWithResponses
	Probes   *probes.ClientWithResponses
	Project  *project.ClientWithResponses
	Request  *request.ClientWithResponses
	Servers  *servers.ClientWithResponses
}

// NewClient creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClient(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewRawClient(server, opts...)
	if err != nil {
		return nil, err
	}

	cwr := &ClientWithResponses{Client: client}
	cwr.Area = area.NewClient(server, client.Client)
	cwr.Backups = backups.NewClient(server, client.Client)
	cwr.Flavors = flavors.NewClient(server, client.Client)
	cwr.Images = images.NewClient(server, client.Client)
	cwr.Keypairs = keypairs.NewClient(server, client.Client)
	cwr.Network = network.NewClient(server, client.Client)
	cwr.Probes = probes.NewClient(server, client.Client)
	cwr.Project = project.NewClient(server, client.Client)
	cwr.Request = request.NewClient(server, client.Client)
	cwr.Servers = servers.NewClient(server, client.Client)

	return cwr, nil
}
