package: resourcemanagement
output: generated/resourcemanagement.gen.go
generate:
  models: true
  client: true
output-options:
  custom-doer:
    enabled: true
    import: common "github.com/SchwarzIT/community-stackit-go-client/internal/common"
    name: "common.Client"
  split-by-tags:
    verbose: false
    enabled: true
    include:
    - Projects
    - Private
  extend-response:
  - field: Error
    type: error
    description: "Aggregated error"
    apply-to: ["*"]
    imports: ["github.com/SchwarzIT/community-stackit-go-client/pkg/validate"]
    set: "validate.DefaultResponseErrorHandler(rsp)"
  copy:
  - from: include/service.go
    to: service.go
    tidy: 
    - replace: "resourcemanagement."
      all: true
  - from: include/projects/validate.go
    to: projects/validate.go
    tidy: 
    - replace: "projects."
      all: true
  - from: include/projects/wait.go
    to: projects/wait.go
    tidy: 
    - replace: "projects."
      all: true
tidy:
  verbose: false
  functions:
  - replace: Id
    with: ID
    all: true
  - replace: GetAllProjects
    with: List
    prefix: true
  - replace: PostProjects
    with: Create
    prefix: true
  - replace: DeleteProjectsContainerID
    with: Delete
    prefix: true
  - replace: PatchProjectsContainerID
    with: Update
    prefix: true
  - replace: GetProjectsContainerID
    with: Get
    prefix: true
  params:
  - replace: Id
    with: ID
    all: true
  schemas:
  - replace: Id
    with: ID
    all: true