package: loadbalancer
output: ../../../../pkg/services/load-balancer/1beta.0.0/loadbalancer.go
generate:
  models: true
  client: true
output-options:
  custom-doer:
    enabled: true
    import: contracts "github.com/SchwarzIT/community-stackit-go-client/pkg/contracts"
    name: "contracts.BaseClientInterface"
  split-by-tags:
    verbose: false
    enabled: true
    include:
      - Project
      - Instances
  extend-response:
    - field: Error
      type: error
      description: "Aggregated error"
      apply-to: ["*"]
      imports:
        - "github.com/SchwarzIT/community-stackit-go-client/pkg/validate"
      set: "validate.DefaultResponseErrorHandler(rsp)"
  copy:
    - from: include/service.go
      to: service.go
      tidy:
        - replace: "loadbalancer."
          all: true
tidy:
  verbose: false
  functions:
    - replace: Id
      with: ID
      all: true
    - replace: APIServiceDisable
      with: DisableProject
      all: true
    - replace: APIServiceEnable
      with: EnableProject
      all: true
    - replace: APIServiceStatus
      with: GetStatus
      all: true
    - replace: APIService
      prefix: true
    - replace: LoadBalancers
      all: true
    - replace: LoadBalancer
      all: true
    - replace: CreateInstances
      with: Create
      all: true
  params:
    - replace: Id
      with: ID
      all: true
  schemas:
    - replace: Id
      with: ID
      all: true
