// Package organizationroles provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/do87/stackit-client-generator version v0.0.3 DO NOT EDIT.
package organizationroles

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/pkg/errors"

	contracts "github.com/SchwarzIT/community-stackit-go-client/pkg/contracts"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/helpers/runtime"
	openapiTypes "github.com/SchwarzIT/community-stackit-go-client/pkg/helpers/types"
	"github.com/SchwarzIT/community-stackit-go-client/pkg/validate"
)

// Defines values for OrgRoleCreateRequestType.
const (
	ORGANIZATION_AUDITOR         OrgRoleCreateRequestType = "organization_auditor"
	ORGANIZATION_BILLING_MANAGER OrgRoleCreateRequestType = "organization_billing_manager"
	ORGANIZATION_MANAGER         OrgRoleCreateRequestType = "organization_manager"
	ORGANIZATION_USER            OrgRoleCreateRequestType = "organization_user"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// OrgID defines model for OrgID.
type OrgID = openapiTypes.UUID

// OrgRoleCreateRequest defines model for OrgRoleCreateRequest.
type OrgRoleCreateRequest struct {
	Type     OrgRoleCreateRequestType `json:"type"`
	UserGUID *UserID                  `json:"userGuid,omitempty"`
	UserName *UserName                `json:"userName,omitempty"`
}

// OrgRoleCreateRequestType defines model for OrgRoleCreateRequest.Type.
type OrgRoleCreateRequestType string

// OrgRoleCreateResponse defines model for OrgRoleCreateResponse.
type OrgRoleCreateResponse struct {
	GUID       RoleID     `json:"guid"`
	OrgID      OrgID      `json:"orgId"`
	PlatformID PlatformID `json:"platformId"`
	ProjectID  ProjectID  `json:"projectId"`
	Region     Region     `json:"region"`
}

// PlatformID defines model for PlatformID.
type PlatformID = openapiTypes.UUID

// ProjectID defines model for ProjectID.
type ProjectID = openapiTypes.UUID

// Region defines model for Region.
type Region = string

// RoleID defines model for RoleID.
type RoleID = openapiTypes.UUID

// UserID defines model for UserID.
type UserID = openapiTypes.UUID

// UserName defines model for UserName.
type UserName = string

// CreateOrgRoleJSONRequestBody defines body for CreateOrgRole for application/json ContentType.
type CreateOrgRoleJSONRequestBody = OrgRoleCreateRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client contracts.BaseClientInterface
}

// NewRawClient Creates a new Client, with reasonable defaults
func NewRawClient(server string, httpClient contracts.BaseClientInterface) *Client {
	// create a client with sane default values
	client := Client{
		Server: server,
		Client: httpClient,
	}
	return &client
}

// The interface specification for the client above.
type rawClientInterface interface {
	// CreateOrgRole request with any body
	CreateOrgRoleRawWithBody(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOrgRoleRaw(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, body CreateOrgRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateOrgRoleRawWithBody(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrgRoleRequestWithBody(ctx, c.Server, projectID, region, organizationID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOrgRoleRaw(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, body CreateOrgRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrgRoleRequest(ctx, c.Server, projectID, region, organizationID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateOrgRoleRequest calls the generic CreateOrgRole builder with application/json body
func NewCreateOrgRoleRequest(ctx context.Context, server string, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, body CreateOrgRoleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrgRoleRequestWithBody(ctx, server, projectID, region, organizationID, "application/json", bodyReader)
}

// NewCreateOrgRoleRequestWithBody generates requests for CreateOrgRole with any type of body
func NewCreateOrgRoleRequestWithBody(ctx context.Context, server string, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "region", runtime.ParamLocationPath, region)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "organizationID", runtime.ParamLocationPath, organizationID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/projects/%s/regions/%s/organizations/%s/roles", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, "POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on rawClientInterface to offer response payloads
type ClientWithResponses struct {
	rawClientInterface
}

// NewClient creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClient(server string, httpClient contracts.BaseClientInterface) *ClientWithResponses {
	return &ClientWithResponses{NewRawClient(server, httpClient)}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateOrgRole request with any body
	CreateOrgRoleWithBody(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrgRoleResponse, error)

	CreateOrgRole(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, body CreateOrgRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrgRoleResponse, error)
}

type CreateOrgRoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *OrgRoleCreateResponse
	JSON400      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateOrgRoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOrgRoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateOrgRoleWithBody request with arbitrary body returning *CreateOrgRoleResponse
func (c *ClientWithResponses) CreateOrgRoleWithBody(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrgRoleResponse, error) {
	rsp, err := c.CreateOrgRoleRawWithBody(ctx, projectID, region, organizationID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return c.ParseCreateOrgRoleResponse(rsp)
}

func (c *ClientWithResponses) CreateOrgRole(ctx context.Context, projectID openapiTypes.UUID, region string, organizationID openapiTypes.UUID, body CreateOrgRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrgRoleResponse, error) {
	rsp, err := c.CreateOrgRoleRaw(ctx, projectID, region, organizationID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return c.ParseCreateOrgRoleResponse(rsp)
}

// ParseCreateOrgRoleResponse parses an HTTP response from a CreateOrgRole call
func (c *ClientWithResponses) ParseCreateOrgRoleResponse(rsp *http.Response) (*CreateOrgRoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOrgRoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest OrgRoleCreateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("body was: %s", string(bodyBytes)))
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("body was: %s", string(bodyBytes)))
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("body was: %s", string(bodyBytes)))
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("body was: %s", string(bodyBytes)))
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("body was: %s", string(bodyBytes)))
		}
		response.JSON500 = &dest

	}

	return response, validate.ResponseObject(response)
}
