package: membership
output: ../../../../pkg/services/membership/v2.0/membership.go
generate:
  models: true
  client: true
output-options:
  custom-doer:
    enabled: true
    import: contracts "github.com/SchwarzIT/community-stackit-go-client/internal/contracts"
    name: "contracts.ClientInterface"
    generics: "contracts.ClientFlowConfig"
  split-by-tags:
    verbose: false
    enabled: true
    include:
    - Membership
  extend-response:
  - field: Error
    type: error
    description: "Aggregated error"
    apply-to: ["*"]
    imports: ["github.com/SchwarzIT/community-stackit-go-client/pkg/validate"]
    set: "validate.DefaultResponseErrorHandler(rsp)"
  copy:
  - from: include/service.go
    to: service.go
    tidy: 
    - replace: "membership."
      all: true
tidy:
  verbose: false
  functions:
  - replace: Id
    with: ID
    all: true
  params:
  - replace: Id
    with: ID
    all: true
  schemas:
  - replace: Id
    with: ID
    all: true