package: postgresflex
output: generated/postgresflex.gen.go
generate:
  models: true
  client: true
output-options:
  custom-doer:
    enabled: true
    import: common "github.com/SchwarzIT/community-stackit-go-client/internal/common"
    name: "common.Client"
  split-by-tags:
    verbose: false
    enabled: true
    include:
    - backups
    - users
    - storage
    - versions
    - flavors
    - instance
  extend-response:
  - field: HasError
    type: error
    description: "Aggregated error"
    apply-to: ["*"]
    imports: ["github.com/SchwarzIT/community-stackit-go-client/pkg/validate"]
    set: "validate.DefaultResponseErrorHandler(rsp)"
  copy:
  - from: include/service.go
    to: service.go
    tidy: 
    - replace: "postgresflex."
      all: true
  - from: include/instance/wait.go
    to: instance/wait.go
    tidy: 
    - replace: "instance."
      all: true
tidy:
  verbose: false
  functions:
  - replace: Id
    with: ID
    suffix: true
  - replace: V1ProjectsProjectId
    with:
    all: true
  - replace: InstancesInstanceId
    with: Instance
    all: true
  - replace: StoragesFlavorID
    with: Flavor
    all: true
  - replace: UsersUserID
    with: User
    all: true
  - replace: InstancesInstanceID
    with: Instance
    all: true
  - replace: BackupsBackupID
    with: Backup
    all: true
  - replace: GetInstanceBackups
    with: List
    prefix: true
  - replace: PutInstanceBackups
    with: Update
    all: true
  - replace: InstanceBackup
    with: 
    suffix: true
  - replace: PostInstances
    with: Create
    all: true
  - replace: PutInstance
    with: Update
    all: true
  - replace: PatchInstance
    with: PatchUpdate
    all: true
  - replace: GetInstances
    with: List
    all: true
  - replace: GetInstance
    with: Get
    all: true
  - replace: DeleteInstance
    with: Delete
    all: true
  - replace: PostInstanceUsers
    with: CreateUser
    prefix: true
  params:
  - replace: Id
    with: ID
    suffix: true
  schemas:
  - replace: Id
    with: ID
    suffix: true
  - replace: Acl
    with: ACL
    suffix: true